AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'spec/fixtures/application/htdocs/stylesheets/**/config.rb'
    - 'config/**/*'
    - 'Vagrantfile'
    - 'vendor/**/*'
  TargetRubyVersion: 2.2
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 160
Metrics/BlockLength:
  Enabled: false
